name: distributed-downloader
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10 <3.12
  - attrs
  - brotli
  - cramjam
  - cython
  - fsspec
  - inflate64
  - openmpi
  - mpi4py
  - multivolumefile
  - opencv
  - pandas
  - pathspec
  - pillow
  - psutil
  - pyarrow
  - pybcj
  - pycryptodomex
  - pyppmd
  - pyspark>=3.4.0
  - python-dotenv
  - pyyaml
  - pyzstd
  - requests
  - setuptools
  - texttable
  - trove-classifiers
  - typing-extensions
  - wheel
  # Development dependencies
  - pytest
  - ruff
